### ISSUE TITLE
Process for cleaning up CI data?

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#82]
As ee2 is converging on its final state, it would be good to have a process for transforming existing data. E.g. when the date format is cleaned up, it would be good to update all of the dates to the new format. Or if there are cases with missing data (e.g. issue #26 missing finished timestamp field), an effort to backfill the data.

**Comment by bio-boris** [comment]
So basically all data should be wiped in ee2_jobs, and then backfilled using njs/ujs using 

https://github.com/kbase/execution_engine2/blob/develop/lib/execution_engine2/db/models/transfer/transfer_ujs_njs.py

This script is not perfect and needs some TLC

**Comment by bio-boris** [comment]
- [ ] would be good to have a process for transforming existing data. E.g. when the date format is cleaned up, it would be good to update all of the dates to the new format. 

- [ ] Or if there are cases with missing data (e.g. issue #26 missing finished timestamp field), an effort to backfill the data.

- [ ] Yes, the backfilling for pre ee2 jobs, but I assume that we would want to preserve ee2 job data since it went live in CI?

**Comment by bio-boris** [comment]
Closing this in favor of https://github.com/kbase/execution_engine2/issues/82
